// templates/svelte-ts/files/src/web/App.svelte
<script lang="ts">
	let count = 0;

	const handleClick = () => {
		count += 1;
	}

  $: {
    window.myAPI.updateTitle(count);
  }
</script>

<div class="container">
  <h1>{count}</h1>
  <button on:click={handleClick}>Count</button>
</div>

<style>
  .container {
    text-align: center;
    font-family: sans-serif;
  }
</style>

// templates/vue-ts/files/src/web/App.vue
<script setup lang="ts">
import { ref, watchEffect } from "vue";

const count = ref(0);

watchEffect(() => {
  window.myAPI.updateTitle(count.value);
});
</script>

<template>
  <div class="container">
    <h1>{{ count }}</h1>
    <button @click="count++">Count</button>
  </div>
</template>

<style scoped>
.container {
  text-align: center;
  font-family: sans-serif;
}
</style>
